services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydb
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

#  frontend:

networks:
  mynetwork:

volumes:
  postgres-data: 