version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:


  frontend:

networks:
  mynetwork:

volumes:
  postgres-data: 