[project]
name = "aula-19"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.2",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]>=2.11.9",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.37.0",
]
